apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scurvy10k-ingress
  namespace: default
spec:
  tls:
    - hosts:
        - true.torfstack.de
      secretName: scurvy10k-tls
  ingressClassName: nginx
  rules:
    - host: true.torfstack.de
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: scurvy10k
              port:
                number: {{ .Values.port }}